[workspace]
members = ["back-end", "front-end"]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
yew = { version = "0.21.0", features = ["wasm-bindgen"] }
actix-web = "4.9.0"
