[build]
target = "./frontend/index.html"
dist = "dist"

[[hooks]]
stage = "build"
command = "npx"
command_arguments = [
    "tailwindcss",
    "-i",
    "./frontend/styles/tailwind.css",
    "-o",
    "./frontend/styles/main.css",
]
